### ISSUE TITLE
Normally-distributed noise

### ISSUE THREAD

**Issue by unixpickle** [wenkesj/evolution#1]
Theoretically, Evolution Strategies requires normally-distributed noise in order to be an accurate gradient estimator. I see [here](https://github.com/wenkesj/evolution/blob/3cd6378216b798fc0d4b70b53e9900bd4a47f7ca/noise/noise.go#L21) that noise is generated as a random number from [-1, 1], which is not a normal distribution (rather, it's a uniform distribution). You can sample a normal distribution with `r.NormFloat64()`. I'd love to see how/if this affects performance.

**Comment by wenkesj** [comment]
This should fix #1, thanks for the input. It definitely has a better purpose and I understand the reasoning theoretically.
